### ISSUE TITLE
Dark Mode Please

### ISSUE THREAD

**Issue by t-kitsune** [ramkumar-kr/react-new-tab-firefox#2]
Please Make a Dark Mode where the background is dark gray, and the text is white

**Comment by ramkumar-kr** [comment]
Hi,

The background color of the page is dictated by the browser and can be changed in [browser's settings](https://support.mozilla.org/kb/change-fonts-and-colors-websites-use).

However, the text color has been overridden to use **#337ab7** since the browser adds different colors for visited and unvisited links.

You are welcome to send a pull request where the text color is dictated by the browser but the colors remain the same for visited and unvisited links.

Closing this issue for now.
